name: Build and Push Docker Image

# Definiert, wann der Workflow ausgeführt werden soll
on:
  push:
    branches:
      - main  # Dieser Workflow wird bei jedem Push in den main-Branch ausgeführt
  pull_request:
    branches:
      - main  # Auch bei Pull Requests in den main-Branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository to the runner
      - name: Check out the repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build the Docker image
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/twiliohook:latest .

      # Push the Docker image to Docker Hub
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/twiliohook:latest
